swagger: "2.0"
info:
  title: "Fibonacci swagger service"
  description: "Offers functionality regarding the Fibonacci sequence"
  version: "1.0.0"

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /fibonacci:
    get:
      operationId: "app.fibonacci.generate"
      parameters:
        - name: terms
          description: Number of terms to generate.
          in: query
          type: "integer"
          required: true
      tags:
        - "numbers"
      summary: ""
      description: "Generate a list of fibonacci numbers"
      responses:
        200:
          description: "Successful generation of fibonacci numbers"
          schema:
            type: "array"
            items:
              properties:
                number:
                  type: "integer"
